DROP TABLE IF EXISTS TBL_USER_ADDITION;
DROP TABLE IF EXISTS TBL_USER;
DROP TABLE IF EXISTS TBL_USER_GROUP;
DROP TABLE IF EXISTS TBL_ORGANIZATION;

CREATE TABLE TBL_USER (
 USER_ID            VARCHAR(32)  NOT NULL
,USER_NAME          VARCHAR(300) NOT NULL
,USER_CURRENT_EMAIL VARCHAR(100)
,INSERT_USER_ID VARCHAR(10)             NOT NULL
,INSERT_DATE    TIMESTAMP   DEFAULT NOW NOT NULL
,UPDATE_USER_ID VARCHAR(10)             NOT NULL
,UPDATE_DATE    TIMESTAMP   DEFAULT NOW NOT NULL
,DELETE_YN      VARCHAR(1)  DEFAULT 'N' NOT NULL
);

CREATE TABLE TBL_USER_ADDITION (
 USER_ID              VARCHAR(32) NOT NULL
,USER_ATTRIBUTE_KEY   VARCHAR(30) NOT NULL
,USER_ATTRIBUTE_VALUE VARCHAR(300)
,INSERT_USER_ID VARCHAR(10)             NOT NULL
,INSERT_DATE    TIMESTAMP   DEFAULT NOW NOT NULL
,UPDATE_USER_ID VARCHAR(10)             NOT NULL
,UPDATE_DATE    TIMESTAMP   DEFAULT NOW NOT NULL
,DELETE_YN      VARCHAR(1)  DEFAULT 'N' NOT NULL
);

ALTER TABLE TBL_USER ADD CONSTRAINT IDX_TBL_USER_PK PRIMARY KEY (USER_ID);

ALTER TABLE TBL_USER_ADDITION ADD CONSTRAINT IDX_TBL_USER_ADDITION_PK PRIMARY KEY (USER_ID);
ALTER TABLE TBL_USER_ADDITION ADD CONSTRAINT IDX_TBL_USER_ADDITION_FK0 FOREIGN KEY (USER_ID) REFERENCES TBL_USER (USER_ID);

CREATE TABLE TBL_USER_GROUP (
 USER_GROUP_PARENT_ID   VARCHAR(4)   NOT NULL
,USER_GROUP_ID          VARCHAR(4)   NOT NULL
,USER_GROUP_NAME        VARCHAR(30)  NOT NULL
,USER_GROUP_DESCRIPTION VARCHAR(300)
,USER_GROUP_SEQUENCE    INTEGER
,USER_GROUP_TYPE        VARCHAR(4)
,INSERT_USER_ID VARCHAR(10)             NOT NULL
,INSERT_DATE    TIMESTAMP   DEFAULT NOW NOT NULL
,UPDATE_USER_ID VARCHAR(10)             NOT NULL
,UPDATE_DATE    TIMESTAMP   DEFAULT NOW NOT NULL
,DELETE_YN      VARCHAR(1)  DEFAULT 'N' NOT NULL
);

ALTER TABLE TBL_USER_GROUP ADD CONSTRAINT IDX_TBL_USER_GROUP_PK PRIMARY KEY (USER_GROUP_PARENT_ID, USER_GROUP_ID);

SELECT  NOW(), a.*
  FROM  INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE a
;