DROP TABLE IF EXISTS TBL_CODE_GROUP;
DROP TABLE IF EXISTS TBL_CODE;
DROP TABLE IF EXISTS TBL_MENU_GROUP;
DROP TABLE IF EXISTS TBL_MENU;

CREATE TABLE TBL_CODE_GROUP (
 CODE_GROUP_ID          VARCHAR(6)   NOT NULL
,CODE_GROUP_NAME        VARCHAR(30)  NOT NULL
,CODE_GROUP_DESCRIPTION VARCHAR(300)
,CODE_GROUP_COLUMN      VARCHAR(30)
,INSERT_USER_ID VARCHAR(10)             NOT NULL
,INSERT_DATE    TIMESTAMP   DEFAULT NOW NOT NULL
,UPDATE_USER_ID VARCHAR(10)             NOT NULL
,UPDATE_DATE    TIMESTAMP   DEFAULT NOW NOT NULL
,DELETE_YN      VARCHAR(1)  DEFAULT 'N' NOT NULL
);

CREATE TABLE TBL_CODE (
 CODE_GROUP_ID    VARCHAR(6)   NOT NULL
,CODE_ID          VARCHAR(4)   NOT NULL
,CODE_NAME        VARCHAR(30)  NOT NULL
,CODE_DESCRIPTION VARCHAR(300)
,CODE_SEQUENCE    INTEGER DEFAULT 0
,INSERT_USER_ID VARCHAR(10)             NOT NULL
,INSERT_DATE    TIMESTAMP   DEFAULT NOW NOT NULL
,UPDATE_USER_ID VARCHAR(10)             NOT NULL
,UPDATE_DATE    TIMESTAMP   DEFAULT NOW NOT NULL
,DELETE_YN      VARCHAR(1)  DEFAULT 'N' NOT NULL
);

ALTER TABLE TBL_CODE_GROUP ADD CONSTRAINT IDX_TBL_CODE_GROUP_PK PRIMARY KEY (CODE_GROUP_ID);

ALTER TABLE TBL_CODE ADD CONSTRAINT IDX_TBL_CODE_PK PRIMARY KEY (CODE_ID);
ALTER TABLE TBL_CODE ADD CONSTRAINT IDX_TBL_CODE_FK0 FOREIGN KEY (CODE_GROUP_ID) REFERENCES TBL_CODE_GROUP (CODE_GROUP_ID);

CREATE TABLE TBL_MENU_GROUP (
 MENU_GROUP_ID          VARCHAR(9)   NOT NULL
,MENU_GROUP_NAME        VARCHAR(30)  NOT NULL
,MENU_GROUP_DESCRIPTION VARCHAR(300)
,MENU_GROUP_SEQUENCE    INTEGER      NOT NULL
,INSERT_USER_ID VARCHAR(10)             NOT NULL
,INSERT_DATE    TIMESTAMP   DEFAULT NOW NOT NULL
,UPDATE_USER_ID VARCHAR(10)             NOT NULL
,UPDATE_DATE    TIMESTAMP   DEFAULT NOW NOT NULL
,DELETE_YN      VARCHAR(1)  DEFAULT 'N' NOT NULL
);

CREATE TABLE TBL_MENU (
 MENU_GROUP_ID    VARCHAR(9)   NOT NULL
,MENU_ID          VARCHAR(9)   NOT NULL
,MENU_NAME        VARCHAR(30)  NOT NULL
,MENU_DESCRIPTION VARCHAR(300)
,MENU_SEQUENCE    INTEGER      NOT NULL
,INSERT_USER_ID VARCHAR(10)             NOT NULL
,INSERT_DATE    TIMESTAMP   DEFAULT NOW NOT NULL
,UPDATE_USER_ID VARCHAR(10)             NOT NULL
,UPDATE_DATE    TIMESTAMP   DEFAULT NOW NOT NULL
,DELETE_YN      VARCHAR(1)  DEFAULT 'N' NOT NULL
);

ALTER TABLE TBL_MENU_GROUP ADD CONSTRAINT IDX_TBL_MENU_GROUP_PK PRIMARY KEY (MENU_GROUP_ID);

ALTER TABLE TBL_MENU ADD CONSTRAINT IDX_TBL_MENU_PK PRIMARY KEY (MENU_ID);
ALTER TABLE TBL_MENU ADD CONSTRAINT IDX_TBL_MENU_FK0 FOREIGN KEY (MENU_GROUP_ID) REFERENCES TBL_MENU_GROUP (MENU_GROUP_ID);
